version: "2.2"
services:
  sea-be:
    container_name: sea-be
    ports:
      - 8080:8080
    image: williamchang80/sea-be:1.1
    environment:
      - spring.datasource.url=[DATBASE_URL]
      - spring.datasource.username=[DATABASE_USERNAME]
      - spring.datasource.password=[DATABASE_PASSWORD]
      - spring.jpa.hibernate.ddl-auto=update
      - server.port=8080
    networks:
      - java_network

  sea-fe:
    container_name: sea-fe
    image: williamchang80/sea-fe:1.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    stdin_open: true
    depends_on:
      - sea-be
    networks:
      - java_network

networks:
  java_network:
    name: java_network
